url: https://hermemories.github.io/
baseurl: marie/

# variables
title: XATSPACE FOR MARIE [TEMPLATE/TITLE]
description: XATSPACE FOR MARIE [TEMPLATE/DESCRIPTION]

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock", "jekyll-theme-windows95.gemspec"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
highlighter: rouge
# excerpt_separator: "\n\n"